import type { ComponentEntry } from "../registry";

export default [
  {
    id: "chip",
    group: "components",
    name: "Chip",
    zh: "筛选芯片",
    description: "可交互的开关按钮：干员一览的筛选栏、语音语种切换。选中 = 主色实底 + 左上角标。",
    css: { files: ["components/chip.css"], status: "ready" },
    vue: { dir: "Chip", components: ["AkChip"], status: "experimental" },
    storybook: "components-chip",
  },
  {
    id: "badge",
    group: "components",
    name: "Badge",
    zh: "计数徽标",
    description: "未读计数 / 未读点。默认黄（提示）不走红；可骑在头像、图标按钮的右上角。",
    css: { files: ["components/badge.css"], status: "ready" },
    vue: { dir: "Badge", components: ["AkBadge"], status: "experimental" },
    storybook: "components-badge",
  },
  {
    id: "card",
    group: "components",
    name: "Card",
    zh: "卡片",
    description: "一件可并列 / 可点的东西：1px 边、直角；封面、眉题、标题栏、页脚、色条、选中角标。",
    css: { files: ["components/card.css"], status: "ready" },
    vue: { dir: "Card", components: ["AkCard", "AkCardGrid"], status: "experimental" },
    storybook: "components-card",
  },
  {
    id: "panel",
    group: "components",
    name: "Panel",
    zh: "面板",
    description: "页面上一块有名字的区域（游戏内 announce panel）：左色条标题栏 + 正文，可反转、可折叠。",
    css: { files: ["components/panel.css"], status: "ready" },
    vue: { dir: "Panel", components: ["AkPanel"], status: "experimental" },
    storybook: "components-panel",
  },
  {
    id: "heading",
    group: "components",
    name: "Heading",
    zh: "区块标题",
    description: "中文标题 + Bender 英文副题，左侧主色粗竖条；模板 / 首页的区块标题。",
    css: { files: ["components/heading.css"], status: "ready" },
    vue: { dir: "Heading", components: ["AkHeading"], status: "experimental" },
    storybook: "components-heading",
  },
  {
    id: "divider",
    group: "components",
    name: "Divider",
    zh: "分隔线",
    description: "1px 线 / 主色短头 / 斜纹带 / 中间带字 / 行内竖线。",
    css: { files: ["components/divider.css"], status: "ready" },
    vue: { dir: "Divider", components: ["AkDivider"], status: "experimental" },
    storybook: "components-divider",
  },
  {
    id: "avatar",
    group: "components",
    name: "Avatar",
    zh: "头像",
    description: "直角方块头像，五档尺寸；没有图时显示文字；头像组后一枚压前一枚。",
    css: { files: ["components/avatar.css"], status: "ready" },
    vue: { dir: "Avatar", components: ["AkAvatar", "AkAvatarGroup"], status: "experimental" },
    storybook: "components-avatar",
  },
  {
    id: "empty",
    group: "components",
    name: "Empty",
    zh: "空状态",
    description: "没有数据 / 没有结果 / 404：虚线框里一枚线稿图标（或大号状态码）+ 标题 + 说明 + 操作。",
    css: { files: ["components/empty.css"], status: "ready" },
    vue: { dir: "Empty", components: ["AkEmpty"], status: "experimental" },
    storybook: "components-empty",
  },
  {
    id: "skeleton",
    group: "components",
    name: "Skeleton",
    zh: "骨架屏",
    description: "内容到之前先占住它的形状：文字行 / 块 / 方 / 圆，两级表面之间扫光。",
    css: { files: ["components/skeleton.css"], status: "ready" },
    vue: { dir: "Skeleton", components: ["AkSkeleton"], status: "experimental" },
    storybook: "components-skeleton",
  },
  {
    id: "spinner",
    group: "components",
    name: "Spinner",
    zh: "加载",
    description: "游戏内 loading 的菱形涟漪 / 三竖条；可带说明，可包住内容做加载层。",
    css: { files: ["components/spinner.css"], status: "ready" },
    vue: { dir: "Spinner", components: ["AkSpinner"], status: "experimental" },
    storybook: "components-spinner",
  },
] satisfies ComponentEntry[];
