import type { ComponentEntry } from "../registry";

/** 通用 · 反馈与浮层 */
export default [
  {
    id: "message",
    group: "components",
    name: "Message",
    zh: "消息",
    description: "界面 / 系统反馈的提示条：左色条 + 淡底，可关闭、可做横幅。编辑写在正文里的提示用 Cbox。",
    css: { files: ["components/message.css"], status: "ready" },
    vue: { dir: "Message", components: ["AkMessage"], status: "experimental" },
    storybook: "components-message",
  },
  {
    id: "tooltip",
    group: "components",
    name: "Tooltip",
    zh: "文字提示",
    description: "悬停 / 聚焦时的一句解释；纯 CSS 的 data-ak-tip 给模板用，Vue 版能放任意内容、四个方向，另有弹出卡片 Popover。",
    css: { files: ["components/tooltip.css"], status: "ready" },
    vue: { dir: "Tooltip", components: ["AkTooltip", "AkPopover"], status: "experimental" },
    storybook: "components-tooltip",
  },
  {
    id: "dropdown",
    group: "components",
    name: "Dropdown",
    zh: "下拉菜单",
    description: "点按钮拉下一列动作 / 链接。左 2px 青条 + 淡底的高亮与侧栏当前项同一语言；键盘按 WAI-ARIA 菜单按钮。",
    css: { files: ["components/dropdown.css"], status: "ready" },
    vue: { dir: "Dropdown", components: ["AkDropdown"], status: "experimental" },
    storybook: "components-dropdown",
  },
  {
    id: "dialog",
    group: "components",
    name: "Dialog",
    zh: "对话框",
    description: "打断当前操作、要求确认的模态窗口：原生 <dialog>，标题栏左色条，底栏右对齐按钮。",
    css: { files: ["components/dialog.css"], status: "ready" },
    vue: { dir: "Dialog", components: ["AkDialog"], status: "experimental" },
    storybook: "components-dialog",
  },
  {
    id: "toast",
    group: "components",
    name: "Toast",
    zh: "轻提示",
    description: "操作之后右下角弹出、几秒后自己消失的一句反馈，底部进度条走完即关。Vue 里用 useToast()。",
    css: { files: ["components/toast.css"], status: "ready" },
    vue: { dir: "Toast", components: ["AkToastProvider"], status: "experimental" },
    storybook: "components-toast",
  },
  {
    id: "progress",
    group: "components",
    name: "Progress",
    zh: "进度",
    description: "完成度 / 数量占比：直角细条（可带标签行、分段、斜纹、不定进度）与环形。",
    css: { files: ["components/progress.css"], status: "ready" },
    vue: { dir: "Progress", components: ["AkProgress"], status: "experimental" },
    storybook: "components-progress",
  },
  {
    id: "stat",
    group: "components",
    name: "Stat",
    zh: "统计数字",
    description: "一个关键数字：小号大写名称 + 大号等宽数字 + 升降变化量；顶边主色条的小卡片，或行内一行。",
    css: { files: ["components/stat.css"], status: "ready" },
    vue: { dir: "Stat", components: ["AkStat", "AkStatRow"], status: "experimental" },
    storybook: "components-stat",
  },
] satisfies ComponentEntry[];
