import type { ComponentEntry } from "../registry";

/** 表单控件：CSS 都在 components/form.css（与 base/forms.css 的裸控件同一套尺寸 / 颜色 / 状态）；单选按钮组借 button.css 的 .ak-btn-group */
export default [
  {
    id: "field",
    group: "components",
    name: "Field",
    zh: "表单字段",
    description: "标签 + 控件 + 说明 / 校验文案。字段里的控件自动关联标签、说明与出错状态。",
    css: { files: ["components/form.css"], status: "ready" },
    vue: { dir: "Field", components: ["AkField"], status: "experimental" },
    storybook: "components-field",
  },
  {
    id: "input",
    group: "components",
    name: "Input",
    zh: "输入框",
    description: "单行 / 多行文字输入。30 / 36 / 44 三档与按钮同高；前后缀与按钮拼成输入组。",
    css: { files: ["components/form.css"], status: "ready" },
    vue: { dir: "Input", components: ["AkInput", "AkInputGroup"], status: "experimental" },
    storybook: "components-input",
  },
  {
    id: "input-number",
    group: "components",
    name: "InputNumber",
    zh: "数字输入",
    description: "常显 − / + 的步进器：等级、信赖、材料数量。方向键步进，Home / End 到上下限。",
    css: { files: ["components/form.css"], status: "ready" },
    vue: { dir: "InputNumber", components: ["AkInputNumber"], status: "experimental" },
    storybook: "components-inputnumber",
  },
  {
    id: "select",
    group: "components",
    name: "Select",
    zh: "下拉选择",
    description: "原生 <select> 换肤：与裸下拉同一枚 ▾，列表与键盘是浏览器自己的。",
    css: { files: ["components/form.css"], status: "ready" },
    vue: { dir: "Select", components: ["AkSelect"], status: "experimental" },
    storybook: "components-select",
  },
  {
    id: "checkbox",
    group: "components",
    name: "Checkbox",
    zh: "复选框",
    description: "18px 直角勾选框，选中主色实底；复选组可限制最多选几个，全选框用半选。",
    css: { files: ["components/form.css"], status: "ready" },
    vue: { dir: "Checkbox", components: ["AkCheckbox", "AkCheckboxGroup"], status: "experimental" },
    storybook: "components-checkbox",
  },
  {
    id: "radio",
    group: "components",
    name: "Radio",
    zh: "单选",
    description: "圆形单选（系统里唯一的圆）；单选按钮组是「列表 / 网格 / 表格」这类分段控件。",
    css: { files: ["components/form.css", "components/button.css"], status: "ready" },
    vue: { dir: "Radio", components: ["AkRadioGroup", "AkRadio", "AkRadioButton"], status: "experimental" },
    storybook: "components-radio",
  },
  {
    id: "switch",
    group: "components",
    name: "Switch",
    zh: "开关",
    description: "方形开关，开 = 游戏内 toggle_on 蓝。立即生效的二元设置。",
    css: { files: ["components/form.css"], status: "ready" },
    vue: { dir: "Switch", components: ["AkSwitch"], status: "experimental" },
    storybook: "components-switch",
  },
  {
    id: "slider",
    group: "components",
    name: "Slider",
    zh: "滑杆",
    description: "原生 range 换肤：方形滑块、4px 轨道。等级、信赖这类在区间里拖的值。",
    css: { files: ["components/form.css"], status: "ready" },
    vue: { dir: "Slider", components: ["AkSlider"], status: "experimental" },
    storybook: "components-slider",
  },
  {
    id: "search",
    group: "components",
    name: "Search",
    zh: "搜索框",
    description: "放大镜 + 输入框 + 快捷键键帽，同页眉里无 JS 时的搜索表单。",
    css: { files: ["components/form.css"], status: "ready" },
    vue: { dir: "Search", components: ["AkSearch"], status: "experimental" },
    storybook: "components-search",
  },
  {
    id: "kbd",
    group: "components",
    name: "Kbd",
    zh: "键帽",
    description: "快捷键提示：直角 1px 边、底边略重、等宽 10px。",
    css: { files: ["components/form.css"], status: "ready" },
    vue: { dir: "Kbd", components: ["AkKbd"], status: "experimental" },
    storybook: "components-kbd",
  },
] satisfies ComponentEntry[];
