import type { ComponentEntry } from "../registry";

export default [
  {
    id: "breadcrumb",
    group: "components",
    name: "Breadcrumb",
    zh: "面包屑",
    description: "当前页在层级里的位置。分隔是 CSS 画的斜角，最后一项是当前页（加粗、aria-current）。",
    css: { files: ["components/breadcrumb.css"], status: "ready" },
    vue: { dir: "Breadcrumb", components: ["AkBreadcrumb", "AkBreadcrumbItem"], status: "experimental" },
    storybook: "components-breadcrumb",
  },
  {
    id: "pagination",
    group: "components",
    name: "Pagination",
    zh: "分页",
    description: "‹ 页码 … 页码 ›：首尾页常驻、当前页居中，当前页主色实底。",
    css: { files: ["components/pagination.css"], status: "ready" },
    vue: { dir: "Pagination", components: ["AkPagination"], status: "experimental" },
    storybook: "components-pagination",
  },
  {
    id: "timeline",
    group: "components",
    name: "Timeline",
    zh: "时间线",
    description: "竖线 + 菱形节点的时间序列：版本、活动、剧情节点。已发生 / 当前为主色实心。",
    css: { files: ["components/timeline.css"], status: "ready" },
    vue: { dir: "Timeline", components: ["AkTimeline", "AkTimelineItem"], status: "experimental" },
    storybook: "components-timeline",
  },
  {
    id: "stepper",
    group: "components",
    name: "Stepper",
    zh: "步骤条",
    description: "带序号的一排步骤 + 连线，展示进度（精英化、专精）。只展示，不可点。",
    css: { files: ["components/stepper.css"], status: "ready" },
    vue: { dir: "Stepper", components: ["AkSteps", "AkStep"], status: "experimental" },
    storybook: "components-stepper",
  },
  {
    id: "accordion",
    group: "components",
    name: "Accordion",
    zh: "折叠面板",
    description: "原生 <details> 折叠块：+ / − 标记，展开后标题行加底色。Vue 版照 Naive 叫 AkCollapse。",
    css: { files: ["components/accordion.css"], status: "ready" },
    vue: { dir: "Accordion", components: ["AkCollapse", "AkCollapseItem"], status: "experimental" },
    storybook: "components-accordion",
  },
  {
    id: "table",
    group: "components",
    name: "Table",
    zh: "数据表",
    description: "模板 / 小部件用的数据表（不是正文 wikitable）：斑马纹、紧凑、数字列、可排序表头。",
    css: { files: ["components/table.css"], status: "ready" },
    vue: { dir: "Table", components: ["AkDataTable"], status: "experimental" },
    storybook: "components-table",
  },
  {
    id: "fab",
    group: "components",
    name: "FAB",
    zh: "回到顶部",
    description: "右下角 44px 反色浮动按钮，滚过一屏淡入。整页那枚由皮肤输出；Vue 版 AkBackTop 给页面里的滚动区域。",
    css: { files: ["components/fab.css"], status: "ready" },
    vue: { dir: "Fab", components: ["AkBackTop"], status: "experimental" },
    storybook: "components-fab",
  },
] satisfies ComponentEntry[];
