import type { ComponentEntry } from "../registry";

/** 方舟 · 干员身份：稀有度 / 职业 / 精英化 / 潜能 / 等级 / 信赖，以及拼起来的干员卡 / 条目 */
export default [
  {
    id: "rarity",
    group: "arknights",
    name: "Rarity",
    zh: "稀有度",
    description: "星级：CSS 星形（游戏黄 / 正文色 / 稀有度色阶）或游戏原图；[data-rarity] 给表格 / 卡片的稀有度色轨。",
    css: { files: ["arknights/rarity.css"], status: "ready" },
    vue: { dir: "Rarity", components: ["AkRarity"], status: "experimental" },
    storybook: "arknights-rarity",
  },
  {
    id: "profession",
    group: "arknights",
    name: "Profession",
    zh: "职业 / 分支",
    description: "职业 / 分支图标（游戏白线稿，亮色主题下反相）与带文字的职业 / 分支名。",
    css: { files: ["arknights/profession.css"], status: "ready" },
    vue: { dir: "Profession", components: ["AkProfession", "AkProfessionLabel"], status: "experimental" },
    storybook: "arknights-profession",
  },
  {
    id: "elite",
    group: "arknights",
    name: "Elite",
    zh: "精英化",
    description: "精英阶段图标 + 标签字「精英二 Lv60」：材料表行头、天赋条件、解锁需求里用。",
    css: { files: ["arknights/elite.css"], status: "ready" },
    vue: { dir: "Elite", components: ["AkElite"], status: "experimental" },
    storybook: "arknights-elite",
  },
  {
    id: "potential",
    group: "arknights",
    name: "Potential",
    zh: "潜能 / 专精",
    description: "潜能 1–6、专精 1–3 的游戏图标，默认坐在深色底座上。",
    css: { files: ["arknights/potential.css"], status: "ready" },
    vue: { dir: "Potential", components: ["AkPotential", "AkSpecialization"], status: "experimental" },
    storybook: "arknights-potential",
  },
  {
    id: "level",
    group: "arknights",
    name: "Level",
    zh: "等级",
    description: "等级读数「LV 90」：LV 小标坐在数字基线上；灰块版与阶段选择器 / 信赖同一条线。",
    css: { files: ["arknights/level.css"], status: "ready" },
    vue: { dir: "Level", components: ["AkLevel"], status: "experimental" },
    storybook: "arknights-level",
  },
  {
    id: "phase-tabs",
    group: "arknights",
    name: "Phase Tabs",
    zh: "阶段选择器",
    description: "精英阶段 E0 / E1 / E2 单选：属性计算器、攻击范围这类按阶段重算的数据用。",
    css: { files: ["arknights/phase-tabs.css"], status: "ready" },
    vue: { dir: "PhaseTabs", components: ["AkPhaseTabs"], status: "experimental" },
    storybook: "arknights-phase-tabs",
  },
  {
    id: "trust",
    group: "arknights",
    name: "Trust",
    zh: "信赖",
    description: "信赖读数：红心 + 百分比，模组 / 档案的解锁需求里用。",
    css: { files: ["arknights/trust.css"], status: "ready" },
    vue: { dir: "Trust", components: ["AkTrust"], status: "experimental" },
    storybook: "arknights-trust",
  },
  {
    id: "pot-list",
    group: "arknights",
    name: "Pot List",
    zh: "潜能提升一览",
    description: "潜能 2–6 各一格（图标 + 小标 + 效果），当前潜能已生效的格子点亮。= 现网 {{潜能提升}}。",
    css: { files: ["arknights/pot-list.css"], status: "ready" },
    vue: { dir: "PotList", components: ["AkPotList", "AkPot"], status: "experimental" },
    storybook: "arknights-pot-list",
    template: "Template:潜能提升",
  },
  {
    id: "op-card",
    group: "arknights",
    name: "Op Card",
    zh: "干员卡",
    description: "游戏干员列表卡：方形头像 + 左上星级 / 左下职业 / 右下精英 + 稀有度色线；网格、异格一览、首页亮点干员。",
    css: { files: ["arknights/op-card.css"], status: "ready" },
    vue: { dir: "OpCard", components: ["AkOpCard", "AkOpGrid"], status: "experimental" },
    storybook: "arknights-op-card",
  },
  {
    id: "op-row",
    group: "arknights",
    name: "Op Row",
    zh: "干员条目",
    description: "干员横向条目：列表 / 表格里一行一位——带稀有度色条的头像 + 名字 + 第二行小字。",
    css: { files: ["arknights/op-row.css"], status: "ready" },
    vue: { dir: "OpRow", components: ["AkOpRow"], status: "experimental" },
    storybook: "arknights-op-row",
  },
] satisfies ComponentEntry[];
