import type { ComponentEntry } from "../registry";

/** 方舟 · 属性与档案：属性表 / 键值表 / 攻击范围 / 模组 / 语音 / 档案 / 档案类卡片 / 剧情对话 */
export default [
  {
    id: "attrs",
    group: "arknights",
    name: "Attrs",
    zh: "属性面板",
    description: "干员属性读数：Bender 大数值 + 英文缩写 / 中文小标，等宽网格、1px 缝线；紧凑版一格一行。",
    css: { files: ["arknights/attrs.css"], status: "ready" },
    vue: { dir: "Attrs", components: ["AkAttrs", "AkAttr"], status: "experimental" },
    storybook: "arknights-attrs",
    template: "Template:属性",
  },
  {
    id: "kv",
    group: "arknights",
    name: "Kv",
    zh: "键值表",
    description: "信息栏 / 档案里的键值对：带框版同现网 infobox，内联版把两三对短值排成一行。",
    css: { files: ["arknights/kv.css"], status: "ready" },
    vue: { dir: "Kv", components: ["AkKv", "AkKvItem"], status: "experimental" },
    storybook: "arknights-kv",
  },
  {
    id: "range",
    group: "arknights",
    name: "Range",
    zh: "攻击范围",
    description: "同现网 Widget:Range：自身实心蓝、可攻击格灰框、范围外不画，只铺外接矩形。",
    css: { files: ["arknights/range.css"], status: "ready" },
    vue: { dir: "Range", components: ["AkRange"], status: "experimental" },
    storybook: "arknights-range",
    template: "Template:干员攻击范围",
  },
  {
    id: "module",
    group: "arknights",
    name: "Module",
    zh: "模组",
    description: "一张卡装完一个模组：型号 + 名称 + 故事（全文阅读）+ 三阶段表 + 解锁任务 + 解锁需求与材料。",
    css: { files: ["arknights/module.css"], status: "ready" },
    vue: { dir: "Module", components: ["AkModule", "AkModuleStage", "AkModuleUnlock"], status: "experimental" },
    storybook: "arknights-module",
    template: "Template:模组",
  },
  {
    id: "voice",
    group: "arknights",
    name: "Voice",
    zh: "语音",
    description: "语音记录列表：播放钮 + 标题 / 语种徽标 / 解锁条件 + 台词；语种切换只换文本与音频，全页同时只放一条。",
    css: { files: ["arknights/voice.css"], status: "ready" },
    vue: { dir: "Voice", components: ["AkVoiceList", "AkVoice"], status: "experimental" },
    storybook: "arknights-voice",
  },
  {
    id: "dossier",
    group: "arknights",
    name: "Dossier",
    zh: "档案",
    description: "人员档案的一段：标题 + 解锁条件 + 正文，未解锁时模糊加斜纹；涂黑文本 .ak-redacted 也在这里。",
    css: { files: ["arknights/dossier.css"], status: "ready" },
    vue: { dir: "Dossier", components: ["AkDossier", "AkRedacted"], status: "experimental" },
    storybook: "arknights-dossier",
    template: "Template:人员档案",
  },
  {
    id: "archive",
    group: "arknights",
    name: "Archive",
    zh: "档案类卡片",
    description: "干员密录 / 悖论模拟 / 未获得时档案：面板头 + 解锁条件 + 正文 + 页脚（阅读 / 关卡 / 首通奖励）。",
    css: { files: ["arknights/archive.css"], status: "ready" },
    vue: { dir: "Archive", components: ["AkArchive", "AkArchivePlay"], status: "experimental" },
    storybook: "arknights-archive",
    template: "Template:干员密录",
  },
  {
    id: "dialogue",
    group: "arknights",
    name: "Dialogue",
    zh: "剧情对话",
    description: "剧情页的对话：说话人一列右对齐、台词一列，旁白灰色斜体；剧透用涂黑。",
    css: { files: ["arknights/dialogue.css"], status: "ready" },
    vue: { dir: "Dialogue", components: ["AkDialogue", "AkDialogueLine"], status: "experimental" },
    storybook: "arknights-dialogue",
  },
] satisfies ComponentEntry[];
