import type { ComponentEntry } from "../registry";

/** 方舟 · 养成与技能：材料表、技能卡 / SP 标签 / 等级选择 / 全等级表 / 参数矩阵、天赋表 / 天赋卡、游戏内富文本 */
export default [
  {
    id: "materials",
    group: "arknights",
    name: "Materials",
    zh: "材料表",
    description: "精英化 / 技能升级 / 专精要的材料：左列阶段或等级，右列一排 40px 道具；可插横跨两列的分段说明。",
    css: { files: ["arknights/materials.css"], status: "ready" },
    vue: { dir: "Materials", components: ["AkMaterials", "AkMaterialsRow", "AkMaterialsDivider"], status: "experimental" },
    storybook: "arknights-materials",
  },
  {
    id: "skill",
    group: "arknights",
    name: "Skill",
    zh: "技能卡",
    description: "一个技能的摘要：图标（SP 类型色描边 + 底条）、名称、SP 类型 / 触发、消耗 / 初始、描述；列表 / 侧栏用，干员页正文用全等级表。",
    css: { files: ["arknights/skill.css"], status: "ready" },
    vue: { dir: "Skill", components: ["AkSkill"], status: "experimental" },
    storybook: "arknights-skill",
  },
  {
    id: "sp",
    group: "arknights",
    name: "Sp",
    zh: "SP 标签",
    description: "技力回复方式（绿自动 / 橙攻击 / 黄受击 / 灰被动）、触发方式，以及消耗 / 初始 / 持续三枚数值芯片。",
    css: { files: ["arknights/sp.css"], status: "ready" },
    vue: { dir: "Sp", components: ["AkSp", "AkSpTrigger", "AkSpValue"], status: "experimental" },
    storybook: "arknights-sp",
  },
  {
    id: "skill-levels",
    group: "arknights",
    name: "SkillLevels",
    zh: "技能等级选择",
    description: "1–7 级 + 专精 Ⅰ–Ⅲ 的单选条。只给需要「当前等级」的场合（高亮全等级表的一行 / 钉住参数矩阵的一列）。",
    css: { files: ["arknights/skill-levels.css"], status: "ready" },
    vue: { dir: "SkillLevels", components: ["AkSkillLevels"], status: "experimental" },
    storybook: "arknights-skilllevels",
  },
  {
    id: "skill-sheet",
    group: "arknights",
    name: "SkillSheet",
    zh: "技能全等级表",
    description: "干员页正文的技能：一张表列完 1–7 级 + 专精 Ⅰ–Ⅲ，初始 / 消耗 / 持续按列对齐，同现网 prts.wiki。",
    css: { files: ["arknights/skill-sheet.css", "arknights/table-numerals.css"], status: "ready" },
    vue: { dir: "SkillSheet", components: ["AkSkillSheet"], status: "experimental" },
    storybook: "arknights-skillsheet",
  },
  {
    id: "skill-matrix",
    group: "arknights",
    name: "SkillMatrix",
    zh: "技能参数矩阵",
    description: "全等级表的另一种对比法：描述只写一遍，参数一行一个、等级一列一个，有变化的格子才亮；悬停 / 钉住一列看该级数值。",
    css: { files: ["arknights/skill-matrix.css"], status: "ready" },
    vue: { dir: "SkillMatrix", components: ["AkSkillMatrix"], status: "experimental" },
    storybook: "arknights-skillmatrix",
  },
  {
    id: "talent-table",
    group: "arknights",
    name: "TalentTable",
    zh: "天赋条件表",
    description: "干员页正文的天赋：一张表列完各精英阶段 / 模组等级下的效果；表头开关切潜能加成、标出算法。",
    css: { files: ["arknights/talent-table.css"], status: "ready" },
    vue: { dir: "TalentTable", components: ["AkTalentTable", "AkCalc"], status: "experimental" },
    storybook: "arknights-talenttable",
  },
  {
    id: "talent",
    group: "arknights",
    name: "Talent",
    zh: "天赋卡",
    description: "一个天赋的摘要：名称 + 解锁条件 + 描述，左侧强调色条。列表 / 侧栏用，干员页正文用条件表。",
    css: { files: ["arknights/talent.css"], status: "ready" },
    vue: { dir: "Talent", components: ["AkTalent"], status: "experimental" },
    storybook: "arknights-talent",
  },
  {
    id: "rich-text",
    group: "arknights",
    name: "RichText",
    zh: "游戏内富文本",
    description: "技能 / 天赋 / 关卡描述里的 <@ba.vup> 这类标记 → .ak-rt-* 配色；Vue 版直接解析游戏原始标记与 blackboard 占位符。",
    css: { files: ["arknights/rich-text.css"], status: "ready" },
    vue: { dir: "RichText", components: ["AkRichText"], status: "experimental" },
    storybook: "arknights-richtext",
  },
] satisfies ComponentEntry[];
