import type { ComponentEntry } from "../registry";

export default [
  {
    id: "stage",
    group: "arknights",
    name: "Stage",
    zh: "关卡",
    description: "关卡卡片（展示字编号 + 名字 + 理智 / 推荐等级）、行内关卡号、理智消耗。",
    css: { files: ["arknights/stage.css"], status: "ready" },
    vue: { dir: "Stage", components: ["AkStage", "AkStageCode", "AkSanity"], status: "experimental" },
    storybook: "arknights-stage",
  },
  {
    id: "enemy",
    group: "arknights",
    name: "Enemy",
    zh: "敌人",
    description: "敌人卡：圆形头像 + 级别 · 编号 + 名字 + 威胁度菱形；精英 / 领袖加左色条。",
    css: { files: ["arknights/enemy.css"], status: "ready" },
    vue: { dir: "Enemy", components: ["AkEnemy"], status: "experimental" },
    storybook: "arknights-enemy",
  },
  {
    id: "camp",
    group: "arknights",
    name: "Camp",
    zh: "阵营",
    description: "势力徽标（游戏白色线稿，亮色下反相）+ 名字；深底方块 / 大号仅徽标。",
    css: { files: ["arknights/camp.css"], status: "ready" },
    vue: { dir: "Camp", components: ["AkCamp"], status: "experimental" },
    storybook: "arknights-camp",
  },
  {
    id: "event",
    group: "arknights",
    name: "Event",
    zh: "活动",
    description: "活动卡（横幅 + 类型 + 标题 + 起止时间，进行中闪红点）与三枚灰块的倒计时。",
    css: { files: ["arknights/event.css"], status: "ready" },
    vue: { dir: "Event", components: ["AkEvent", "AkCountdown"], status: "experimental" },
    storybook: "arknights-event",
  },
  {
    id: "news",
    group: "arknights",
    name: "News",
    zh: "新闻横幅",
    description: "游戏主界面的 Breaking news 横幅：矩形红块 + 反色底的一行正文，只装一条。",
    css: { files: ["arknights/news.css"], status: "ready" },
    vue: { dir: "News", components: ["AkNews"], status: "experimental" },
    storybook: "arknights-news",
  },
  {
    id: "hero",
    group: "arknights",
    name: "Hero",
    zh: "大标题横幅",
    description: "官网风页头横幅：黑底 + 大号拉丁标题 + 青色横条，右侧青色色面叠网点。",
    css: { files: ["arknights/hero.css"], status: "ready" },
    vue: { dir: "Hero", components: ["AkHero"], status: "experimental" },
    storybook: "arknights-hero",
  },
] satisfies ComponentEntry[];
